---
abstract: 'A simple client library for the ProximoBus API.'
author:
  - 'Sam Kimbrel (kimbrel@me.com)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ProximoBus
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  JSON: 0
  LWP::UserAgent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/skimbrel/WWW-ProximoBus.git
version: 0.01
